---
- name: Setup hadoop/spark master node
  hosts: debian-master
  remote_user: hadoop
  sudo: yes

  roles:
#    - java8
#    - spark
    - common
#    - scala

- name: Setup hadoop/spark data node
  hosts: debian-slave-1
  remote_user: hadoop
  sudo: yes

  roles:
#    - java8
#    - spark
    - common

- name: Setup hadoop/spark data node
  hosts: debian-slave-2
  remote_user: hadoop
  sudo: yes

  roles:
 #   - java8
  #  - spark
    - common
