---
- name: Setup hadoop/spark master node
  hosts: debian-master
  remote_user: hadoop
  sudo: no

  roles:
    - java8

- name: Setup hadoop/spark data node
  hosts: debian-slave-1
  remote_user: hadoop
  sudo: no

  roles:
    - java8

- name: Setup hadoop/spark data node
  hosts: debian-slave-2
  remote_user: hadoop
  sudo: no

  roles:
    - java8